version: "3"
services:
  main:
    build: ./
    volumes:
    - "./apicaddy-cert.pem:/etc/nginx/apicaddy-cert.pem"
    - "./apicaddy-key.pem:/etc/nginx/apicaddy-key.pem"
    - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - "443:443"
  web1:
    build: 
      context: ./web1
    ports:
    - "8180:80"
  web2:
    build: 
      context: ./web2
    ports:
    - "8181:80"



